[2024-05-09T02:04:56.431+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:04:56.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:04:56.436+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:04:56.436+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:04:56.469+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:04:56.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:04:56.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:04:56.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.118 seconds
[2024-05-09T02:05:26.734+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:05:26.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:05:26.752+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:05:26.750+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:05:26.781+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:05:26.775+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:05:26.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:05:26.838+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.128 seconds
[2024-05-09T02:05:56.886+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:05:56.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:05:56.889+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:05:56.888+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:05:56.900+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:05:56.897+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:05:56.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:05:56.919+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-05-09T02:06:27.121+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:06:27.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:06:27.126+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:06:27.126+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:06:27.137+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:06:27.134+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:06:27.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:06:27.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-09T02:06:57.277+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:06:57.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:06:57.282+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:06:57.282+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:06:57.294+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:06:57.291+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:06:57.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:06:57.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-09T02:07:27.440+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:07:27.442+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:07:27.443+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:07:27.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:07:27.454+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:07:27.452+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:07:27.455+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:07:27.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-05-09T02:07:57.605+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:07:57.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:07:57.610+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:07:57.609+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:07:57.620+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:07:57.618+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:07:57.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:07:57.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-05-09T02:08:27.771+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:08:27.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:08:27.794+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:08:27.794+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:08:27.811+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:08:27.807+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:08:27.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:08:27.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.067 seconds
[2024-05-09T02:08:57.941+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:08:57.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:08:57.945+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:08:57.945+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:08:57.957+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:08:57.954+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:08:57.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:08:57.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-05-09T02:09:28.112+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:09:28.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:09:28.115+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:09:28.115+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:09:28.130+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:09:28.126+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:09:28.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:09:28.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-05-09T02:09:58.352+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:09:58.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:09:58.355+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:09:58.354+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:09:58.367+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:09:58.364+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:09:58.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:09:58.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-09T02:10:28.532+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:10:28.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:10:28.538+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:10:28.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:10:28.554+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:10:28.551+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:10:28.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:10:28.570+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-05-09T02:10:58.683+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:10:58.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:10:58.685+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:10:58.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:10:58.697+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:10:58.694+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:10:58.698+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:10:58.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-05-09T02:11:28.868+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:11:28.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:11:28.872+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:11:28.872+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:11:28.884+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:11:28.881+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:11:28.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:11:28.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.054 seconds
[2024-05-09T02:11:59.021+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:11:59.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:11:59.024+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:11:59.024+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:11:59.035+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:11:59.033+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:11:59.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:11:59.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-09T02:12:29.216+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:12:29.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:12:29.219+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:12:29.218+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:12:29.230+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:12:29.228+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:12:29.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:12:29.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-09T02:12:59.383+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:12:59.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:12:59.386+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:12:59.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:12:59.399+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:12:59.396+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:12:59.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:12:59.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-09T02:13:29.540+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:13:29.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:13:29.542+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:13:29.542+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:13:29.554+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:13:29.550+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:13:29.556+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:13:29.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-05-09T02:13:59.701+0000] {processor.py:161} INFO - Started process (PID=163) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:13:59.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:13:59.703+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:13:59.703+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:13:59.719+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:13:59.713+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:13:59.720+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:13:59.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-09T02:14:29.862+0000] {processor.py:161} INFO - Started process (PID=170) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:14:29.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:14:29.865+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:14:29.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:14:29.879+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:14:29.876+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:14:29.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:14:29.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-05-09T02:15:00.157+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:15:00.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:15:00.162+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:15:00.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:15:00.180+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:15:00.177+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:15:00.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:15:00.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.113 seconds
[2024-05-09T02:15:30.341+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:15:30.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:15:30.345+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:15:30.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:15:30.362+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:15:30.359+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:15:30.363+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:15:30.385+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-05-09T02:16:00.513+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:16:00.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:16:00.533+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:16:00.522+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:16:00.565+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:16:00.553+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:16:00.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:16:00.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.246 seconds
[2024-05-09T02:16:30.929+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:16:30.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:16:30.936+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:16:30.933+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:16:30.973+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:16:30.964+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:16:30.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:16:31.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.232 seconds
[2024-05-09T02:17:01.418+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:17:01.419+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:17:01.421+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:17:01.420+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:17:01.451+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:17:01.445+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:17:01.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:17:01.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.065 seconds
[2024-05-09T02:17:31.630+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:17:31.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:17:31.638+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:17:31.637+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:17:31.669+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:17:31.663+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:17:31.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:17:31.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.101 seconds
[2024-05-09T02:18:03.995+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:18:04.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:18:04.251+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:18:04.229+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:18:04.493+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:18:04.442+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:18:04.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:18:05.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 1.801 seconds
[2024-05-09T02:18:35.444+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:18:35.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:18:35.449+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:18:35.449+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:18:35.467+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:18:35.463+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:18:35.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:18:35.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.087 seconds
[2024-05-09T02:19:05.718+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:19:05.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:19:05.725+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:19:05.724+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:19:05.748+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:19:05.743+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:19:05.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:19:05.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.107 seconds
[2024-05-09T02:19:35.878+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:19:35.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:19:35.885+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:19:35.884+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:19:35.897+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:19:35.895+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:19:35.899+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:19:35.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-05-09T02:20:06.026+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:20:06.027+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:20:06.029+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:20:06.029+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:20:06.044+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:20:06.040+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:20:06.046+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:20:06.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2024-05-09T02:20:36.177+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:20:36.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:20:36.180+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:20:36.180+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:20:36.192+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:20:36.190+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:20:36.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:20:36.210+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-05-09T02:21:06.381+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:21:06.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:21:06.385+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:21:06.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:21:06.405+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:21:06.400+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:21:06.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:21:06.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.056 seconds
[2024-05-09T02:21:36.538+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:21:36.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:21:36.543+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:21:36.543+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:21:36.557+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:21:36.554+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:21:36.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:21:36.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-09T02:22:06.712+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:22:06.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:22:06.715+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:22:06.714+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:22:06.726+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:22:06.723+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:22:06.727+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:22:06.745+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-05-09T02:22:36.881+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:22:36.881+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:22:36.883+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:22:36.883+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:22:36.895+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:22:36.892+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:22:36.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:22:36.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-05-09T02:23:07.034+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:23:07.036+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:23:07.037+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:23:07.037+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:23:07.050+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:23:07.047+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:23:07.051+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:23:07.068+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-05-09T02:23:37.183+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:23:37.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:23:37.187+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:23:37.186+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:23:37.198+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:23:37.196+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:23:37.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:23:37.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-05-09T02:24:07.373+0000] {processor.py:161} INFO - Started process (PID=303) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:24:07.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:24:07.376+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:24:07.375+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:24:07.388+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:24:07.385+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:24:07.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:24:07.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-09T02:24:37.539+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:24:37.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:24:37.542+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:24:37.542+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:24:37.558+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:24:37.556+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:24:37.559+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:24:37.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-09T02:25:07.715+0000] {processor.py:161} INFO - Started process (PID=317) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:25:07.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:25:07.718+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:25:07.718+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:25:07.730+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:25:07.727+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:25:07.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:25:07.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-05-09T02:25:37.873+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:25:37.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:25:37.876+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:25:37.875+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:25:37.891+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:25:37.888+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:25:37.892+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:25:37.908+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-09T02:26:08.068+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:26:08.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:26:08.071+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:26:08.070+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:26:08.082+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:26:08.080+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:26:08.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:26:08.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-05-09T02:26:38.237+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:26:38.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:26:38.241+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:26:38.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:26:38.255+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:26:38.251+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:26:38.256+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:26:38.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-05-09T02:27:08.399+0000] {processor.py:161} INFO - Started process (PID=345) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:27:08.400+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:27:08.402+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:27:08.402+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:27:08.421+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:27:08.416+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:27:08.423+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:27:08.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.053 seconds
[2024-05-09T02:27:38.577+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:27:38.578+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:27:38.579+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:27:38.579+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:27:38.591+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:27:38.589+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:27:38.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:27:38.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-05-09T02:28:08.842+0000] {processor.py:161} INFO - Started process (PID=359) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:28:08.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:28:08.845+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:28:08.844+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:28:08.857+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:28:08.855+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:28:08.859+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:28:08.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-05-09T02:28:39.021+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:28:39.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:28:39.027+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:28:39.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:28:39.049+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:28:39.045+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:28:39.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:28:39.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.062 seconds
[2024-05-09T02:29:09.175+0000] {processor.py:161} INFO - Started process (PID=373) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:29:09.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:29:09.178+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:29:09.178+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:29:09.192+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:29:09.189+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:29:09.193+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:29:09.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-09T02:29:39.389+0000] {processor.py:161} INFO - Started process (PID=380) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:29:39.390+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:29:39.392+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:29:39.392+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:29:39.409+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:29:39.404+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:29:39.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:29:39.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-09T02:30:09.586+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:30:09.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:30:09.589+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:30:09.589+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:30:09.601+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:30:09.598+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:30:09.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:30:09.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-05-09T02:30:39.745+0000] {processor.py:161} INFO - Started process (PID=394) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:30:39.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:30:39.747+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:30:39.747+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:30:39.758+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:30:39.756+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:30:39.759+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:30:39.775+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-05-09T02:31:09.920+0000] {processor.py:161} INFO - Started process (PID=401) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:31:09.921+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:31:09.923+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:31:09.923+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:31:09.934+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:31:09.932+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:31:09.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:31:09.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-05-09T02:31:40.078+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:31:40.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:31:40.081+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:31:40.081+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:31:40.093+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:31:40.091+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:31:40.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:31:40.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-05-09T02:32:10.259+0000] {processor.py:161} INFO - Started process (PID=415) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:32:10.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:32:10.267+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:32:10.266+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:32:10.285+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:32:10.281+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:32:10.286+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:32:10.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2024-05-09T02:32:40.398+0000] {processor.py:161} INFO - Started process (PID=422) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:32:40.399+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:32:40.401+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:32:40.400+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:32:40.413+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:32:40.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:32:40.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:32:40.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-09T02:33:10.614+0000] {processor.py:161} INFO - Started process (PID=429) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:33:10.616+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:33:10.618+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:33:10.618+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:33:10.633+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:33:10.630+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:33:10.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:33:10.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2024-05-09T02:33:40.774+0000] {processor.py:161} INFO - Started process (PID=436) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:33:40.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:33:40.776+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:33:40.776+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:33:40.789+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:33:40.787+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:33:40.790+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:33:40.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-05-09T02:34:11.088+0000] {processor.py:161} INFO - Started process (PID=443) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:34:11.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:34:11.093+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:34:11.092+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:34:11.141+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:34:11.132+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:34:11.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:34:11.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.113 seconds
[2024-05-09T02:34:41.246+0000] {processor.py:161} INFO - Started process (PID=450) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:34:41.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:34:41.249+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:34:41.248+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:34:41.262+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:34:41.259+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:34:41.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:34:41.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.039 seconds
[2024-05-09T02:35:11.446+0000] {processor.py:161} INFO - Started process (PID=457) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:35:11.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:35:11.448+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:35:11.448+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:35:11.461+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:35:11.458+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:35:11.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:35:11.476+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.036 seconds
[2024-05-09T02:35:41.643+0000] {processor.py:161} INFO - Started process (PID=464) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T02:35:41.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T02:35:41.645+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:35:41.645+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T02:35:41.656+0000] {logging_mixin.py:188} INFO - [2024-05-09T02:35:41.654+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T02:35:41.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T02:35:41.673+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-05-09T04:06:25.845+0000] {processor.py:161} INFO - Started process (PID=465) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:06:25.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:06:25.865+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:06:25.864+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:06:25.937+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:06:25.901+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:06:25.942+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:06:26.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.379 seconds
[2024-05-09T04:06:56.676+0000] {processor.py:161} INFO - Started process (PID=473) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:06:56.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:06:56.691+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:06:56.691+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:06:56.705+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:06:56.702+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:06:56.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:06:56.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2024-05-09T04:07:26.837+0000] {processor.py:161} INFO - Started process (PID=480) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:07:26.838+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:07:26.840+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:07:26.840+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:07:26.857+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:07:26.852+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:07:26.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:07:26.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-09T04:07:57.024+0000] {processor.py:161} INFO - Started process (PID=487) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:07:57.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:07:57.027+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:07:57.026+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:07:57.039+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:07:57.036+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:07:57.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:07:57.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-05-09T04:08:27.190+0000] {processor.py:161} INFO - Started process (PID=494) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:08:27.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:08:27.193+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:08:27.192+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:08:27.204+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:08:27.202+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:08:27.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:08:27.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-05-09T04:08:57.343+0000] {processor.py:161} INFO - Started process (PID=501) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:08:57.344+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:08:57.346+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:08:57.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:08:57.358+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:08:57.356+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:08:57.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:08:57.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-05-09T04:09:27.508+0000] {processor.py:161} INFO - Started process (PID=508) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:09:27.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:09:27.511+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:09:27.511+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:09:27.526+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:09:27.523+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:09:27.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:09:27.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-09T04:09:57.680+0000] {processor.py:161} INFO - Started process (PID=515) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:09:57.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:09:57.683+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:09:57.683+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:09:57.696+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:09:57.693+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:09:57.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:09:57.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-05-09T04:10:27.848+0000] {processor.py:161} INFO - Started process (PID=522) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:10:27.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:10:27.850+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:10:27.850+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:10:27.864+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:10:27.861+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:10:27.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:10:27.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.037 seconds
[2024-05-09T04:10:58.017+0000] {processor.py:161} INFO - Started process (PID=529) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:10:58.017+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:10:58.019+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:10:58.019+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:10:58.031+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:10:58.028+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:10:58.032+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:10:58.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.035 seconds
[2024-05-09T04:11:28.222+0000] {processor.py:161} INFO - Started process (PID=536) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:11:28.223+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:11:28.225+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:11:28.224+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:11:28.241+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:11:28.238+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 7, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:11:28.242+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:11:28.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-09T04:11:38.289+0000] {processor.py:161} INFO - Started process (PID=543) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:11:38.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:11:38.291+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:11:38.291+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:11:38.334+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:11:38.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import crawl
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:11:38.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:11:38.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.068 seconds
[2024-05-09T04:13:34.508+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:13:34.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:13:34.514+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:13:34.513+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:13:34.539+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:13:34.532+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import crawl
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:13:34.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:13:34.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.065 seconds
[2024-05-09T04:14:04.878+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:14:04.883+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:14:04.913+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:14:04.907+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:14:04.976+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:14:04.962+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import crawl
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:14:04.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:14:05.080+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.273 seconds
[2024-05-09T04:14:35.255+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:14:35.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:14:35.260+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:14:35.259+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:14:35.279+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:14:35.273+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import crawl
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:14:35.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:14:35.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.081 seconds
[2024-05-09T04:15:05.411+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:15:05.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:15:05.413+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:15:05.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:15:05.429+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:15:05.424+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import crawl
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:15:05.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:15:05.450+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-05-09T04:15:35.637+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:15:35.638+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:15:35.641+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:15:35.640+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:15:35.657+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:15:35.652+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import crawl
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:15:35.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:15:35.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.092 seconds
[2024-05-09T04:16:05.747+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:16:05.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:16:05.750+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:16:05.750+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:16:05.767+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:16:05.763+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import crawl
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:16:05.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:16:05.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-05-09T04:16:35.891+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:16:35.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:16:35.894+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:16:35.894+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:16:35.909+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:16:35.904+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import crawl
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:16:35.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:16:35.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-09T04:16:46.003+0000] {processor.py:161} INFO - Started process (PID=78) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:16:46.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:16:46.007+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:16:46.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:16:46.032+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:16:46.027+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:16:46.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:16:46.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2024-05-09T04:18:07.599+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:18:07.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:18:07.605+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:18:07.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:18:07.629+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:18:07.623+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:18:07.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:18:07.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.063 seconds
[2024-05-09T04:18:17.771+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:18:17.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:18:17.785+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:18:17.783+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:18:17.826+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:18:17.817+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:18:17.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:18:17.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.158 seconds
[2024-05-09T04:18:48.075+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:18:48.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:18:48.081+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:18:48.078+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:18:48.108+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:18:48.101+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:18:48.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:18:48.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.088 seconds
[2024-05-09T04:19:18.277+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:19:18.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:19:18.285+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:19:18.285+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:19:18.315+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:19:18.308+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:19:18.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:19:18.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.079 seconds
[2024-05-09T04:19:48.464+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:19:48.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:19:48.467+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:19:48.467+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:19:48.489+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:19:48.482+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:19:48.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:19:48.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.072 seconds
[2024-05-09T04:20:18.672+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:20:18.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:20:18.684+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:20:18.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:20:18.712+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:20:18.705+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:20:18.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:20:18.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.112 seconds
[2024-05-09T04:20:48.839+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:20:48.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:20:48.846+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:20:48.843+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:20:48.869+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:20:48.862+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:20:48.871+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:20:48.897+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.064 seconds
[2024-05-09T04:21:18.996+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:21:18.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:21:18.999+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:21:18.998+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:21:19.014+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:21:19.009+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:21:19.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:21:19.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-09T04:21:49.179+0000] {processor.py:161} INFO - Started process (PID=86) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:21:49.180+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:21:49.183+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:21:49.183+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:21:49.201+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:21:49.196+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:21:49.203+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:21:49.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-05-09T04:22:19.344+0000] {processor.py:161} INFO - Started process (PID=93) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:22:19.345+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:22:19.347+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:22:19.347+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:22:19.364+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:22:19.360+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:22:19.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:22:19.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-05-09T04:22:49.539+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:22:49.540+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:22:49.543+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:22:49.542+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:22:49.562+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:22:49.557+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:22:49.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:22:49.588+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.056 seconds
[2024-05-09T04:26:13.005+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:26:13.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:26:13.013+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:26:13.013+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:26:13.039+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:26:13.030+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:26:13.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:26:13.073+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.086 seconds
[2024-05-09T04:26:43.252+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:26:43.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:26:43.258+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:26:43.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:26:43.279+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:26:43.273+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:26:43.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:26:43.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.061 seconds
[2024-05-09T04:27:13.401+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:27:13.402+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:27:13.404+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:27:13.403+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:27:13.418+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:27:13.414+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:27:13.419+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:27:13.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-09T04:27:43.597+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:27:43.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:27:43.602+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:27:43.601+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:27:43.624+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:27:43.619+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:27:43.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:27:43.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.096 seconds
[2024-05-09T04:28:13.746+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/test_dag.py
[2024-05-09T04:28:13.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-09T04:28:13.752+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:28:13.751+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-09T04:28:13.778+0000] {logging_mixin.py:188} INFO - [2024-05-09T04:28:13.770+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-09T04:28:13.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-09T04:28:13.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.094 seconds
