[2024-05-18T10:02:24.630+0000] {processor.py:161} INFO - Started process (PID=29) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:02:24.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:02:24.635+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:02:24.634+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:02:24.671+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:02:24.656+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:02:24.673+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:02:24.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.094 seconds
[2024-05-18T10:02:55.355+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:02:55.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:02:55.385+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:02:55.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:02:55.449+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:02:55.437+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:02:55.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:02:55.536+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.226 seconds
[2024-05-18T10:03:25.780+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:03:25.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:03:25.784+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:03:25.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:03:25.808+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:03:25.802+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:03:25.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:03:25.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2024-05-18T10:03:55.968+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:03:55.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:03:55.973+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:03:55.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:03:56.009+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:03:56.001+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:03:56.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:03:56.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.216 seconds
[2024-05-18T10:04:26.402+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:04:26.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:04:26.409+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:04:26.409+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:04:26.447+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:04:26.437+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:04:26.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:04:26.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.079 seconds
[2024-05-18T10:04:56.547+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:04:56.550+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:04:56.552+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:04:56.551+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:04:56.566+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:04:56.562+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:04:56.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:04:56.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-18T10:05:26.778+0000] {processor.py:161} INFO - Started process (PID=77) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:05:26.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:05:26.781+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:05:26.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:05:26.804+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:05:26.797+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:05:26.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:05:26.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.075 seconds
[2024-05-18T10:05:57.338+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:05:57.339+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:05:57.343+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:05:57.342+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:05:57.370+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:05:57.365+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:05:57.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:05:57.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.082 seconds
[2024-05-18T10:06:27.621+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:06:27.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:06:27.624+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:06:27.624+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:06:27.645+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:06:27.640+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:06:27.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:06:27.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-05-18T10:06:57.866+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:06:57.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:06:57.873+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:06:57.873+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:06:57.902+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:06:57.895+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:06:57.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:06:57.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.088 seconds
[2024-05-18T10:07:28.125+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:07:28.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:07:28.128+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:07:28.127+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:07:28.147+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:07:28.142+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:07:28.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:07:28.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-18T10:07:58.295+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:07:58.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:07:58.300+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:07:58.300+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:07:58.337+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:07:58.327+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:07:58.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:07:58.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.088 seconds
[2024-05-18T10:08:28.472+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:08:28.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:08:28.475+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:08:28.475+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:08:28.492+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:08:28.487+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:08:28.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:08:28.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-18T10:08:58.696+0000] {processor.py:161} INFO - Started process (PID=126) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:08:58.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:08:58.699+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:08:58.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:08:58.717+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:08:58.712+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:08:58.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:08:58.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-05-18T10:09:28.883+0000] {processor.py:161} INFO - Started process (PID=133) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:09:28.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:09:28.886+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:09:28.885+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:09:28.904+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:09:28.899+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:09:28.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:09:28.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-18T10:09:59.067+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:09:59.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:09:59.071+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:09:59.070+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:09:59.091+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:09:59.085+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:09:59.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:09:59.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
[2024-05-18T10:10:29.286+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:10:29.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:10:29.294+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:10:29.293+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:10:29.330+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:10:29.321+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:10:29.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:10:29.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.089 seconds
[2024-05-18T10:10:59.458+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:10:59.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:10:59.461+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:10:59.461+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:10:59.493+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:10:59.484+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:10:59.495+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:10:59.518+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2024-05-18T10:11:29.775+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:11:29.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:11:29.779+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:11:29.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:11:29.803+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:11:29.798+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:11:29.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:11:29.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.060 seconds
[2024-05-18T10:12:00.082+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:12:00.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:12:00.086+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:12:00.086+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:12:00.108+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:12:00.103+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:12:00.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:12:00.154+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.077 seconds
[2024-05-18T10:12:30.311+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:12:30.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:12:30.314+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:12:30.314+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:12:30.333+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:12:30.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:12:30.335+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:12:30.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-18T10:13:00.548+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:13:00.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:13:00.557+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:13:00.557+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:13:00.594+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:13:00.588+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:13:00.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:13:00.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.084 seconds
[2024-05-18T10:13:30.707+0000] {processor.py:161} INFO - Started process (PID=190) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T10:13:30.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T10:13:30.709+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:13:30.709+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T10:13:30.729+0000] {logging_mixin.py:188} INFO - [2024-05-18T10:13:30.724+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T10:13:30.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T10:13:30.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-18T11:37:28.134+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:37:28.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:37:28.147+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:37:28.147+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:37:28.189+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:37:28.181+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:37:28.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:37:28.284+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.167 seconds
[2024-05-18T11:37:58.413+0000] {processor.py:161} INFO - Started process (PID=198) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:37:58.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:37:58.421+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:37:58.420+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:37:58.472+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:37:58.460+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:37:58.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:37:58.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.248 seconds
[2024-05-18T11:38:28.840+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:38:28.841+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:38:28.843+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:38:28.843+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:38:28.862+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:38:28.857+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:38:28.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:38:28.881+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2024-05-18T11:38:59.004+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:38:59.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:38:59.007+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:38:59.007+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:38:59.027+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:38:59.022+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:38:59.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:38:59.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-18T11:39:29.257+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:39:29.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:39:29.269+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:39:29.266+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:39:29.343+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:39:29.322+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:39:29.350+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:39:29.434+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.185 seconds
[2024-05-18T11:39:59.683+0000] {processor.py:161} INFO - Started process (PID=226) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:39:59.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:39:59.687+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:39:59.687+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:39:59.705+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:39:59.700+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:39:59.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:39:59.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-18T11:40:30.012+0000] {processor.py:161} INFO - Started process (PID=233) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:40:30.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:40:30.015+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:40:30.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:40:30.054+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:40:30.045+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:40:30.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:40:30.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.094 seconds
[2024-05-18T11:41:00.230+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:41:00.231+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:41:00.233+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:41:00.233+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:41:00.251+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:41:00.246+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:41:00.253+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:41:00.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-18T11:41:30.472+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:41:30.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:41:30.475+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:41:30.475+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:41:30.494+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:41:30.489+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:41:30.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:41:30.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.047 seconds
[2024-05-18T11:42:00.683+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:42:00.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:42:00.686+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:42:00.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:42:00.700+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:42:00.696+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:42:00.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:42:00.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.040 seconds
[2024-05-18T11:42:31.176+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:42:31.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:42:31.183+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:42:31.181+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:42:31.213+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:42:31.207+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:42:31.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:42:31.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.086 seconds
[2024-05-18T11:43:01.463+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:43:01.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:43:01.469+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:43:01.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:43:01.496+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:43:01.490+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:43:01.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:43:01.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.069 seconds
[2024-05-18T11:43:31.937+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:43:31.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:43:31.944+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:43:31.943+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:43:31.965+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:43:31.960+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:43:31.967+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:43:31.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.070 seconds
[2024-05-18T11:44:02.229+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:44:02.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:44:02.232+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:44:02.232+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:44:02.254+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:44:02.249+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:44:02.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:44:02.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2024-05-18T11:44:32.552+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:44:32.555+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:44:32.558+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:44:32.557+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:44:32.588+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:44:32.578+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:44:32.591+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:44:32.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.086 seconds
[2024-05-18T11:45:02.825+0000] {processor.py:161} INFO - Started process (PID=296) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:45:02.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:45:02.829+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:45:02.828+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:45:02.846+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:45:02.841+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:45:02.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:45:02.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-18T11:45:33.030+0000] {processor.py:161} INFO - Started process (PID=303) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:45:33.031+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:45:33.032+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:45:33.032+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:45:33.046+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:45:33.042+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:45:33.048+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:45:33.063+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.038 seconds
[2024-05-18T11:46:03.196+0000] {processor.py:161} INFO - Started process (PID=310) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:46:03.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:46:03.199+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:46:03.199+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:46:03.290+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:46:03.226+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:46:03.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:46:03.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.140 seconds
[2024-05-18T11:46:33.819+0000] {processor.py:161} INFO - Started process (PID=317) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:46:33.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:46:33.824+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:46:33.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:46:33.852+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:46:33.847+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:46:33.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:46:33.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.066 seconds
[2024-05-18T11:47:04.457+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:47:04.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:47:04.461+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:47:04.460+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:47:04.486+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:47:04.479+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:47:04.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:47:04.510+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.060 seconds
[2024-05-18T11:47:35.393+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:47:35.394+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:47:35.396+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:47:35.396+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:47:35.427+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:47:35.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:47:35.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:47:35.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.068 seconds
[2024-05-18T11:48:05.538+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:48:05.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:48:05.542+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:48:05.542+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:48:05.572+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:48:05.562+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:48:05.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:48:05.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.067 seconds
[2024-05-18T11:48:36.182+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:48:36.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:48:36.188+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:48:36.188+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:48:36.211+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:48:36.205+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:48:36.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:48:36.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.057 seconds
[2024-05-18T11:49:06.852+0000] {processor.py:161} INFO - Started process (PID=353) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:49:06.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:49:06.855+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:49:06.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:49:06.878+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:49:06.872+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:49:06.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:49:06.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.055 seconds
[2024-05-18T11:49:37.903+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:49:37.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:49:37.910+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:49:37.910+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:49:37.945+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:49:37.935+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:49:37.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:49:37.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.082 seconds
[2024-05-18T11:50:08.811+0000] {processor.py:161} INFO - Started process (PID=369) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:50:08.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:50:08.816+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:50:08.815+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:50:08.846+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:50:08.837+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:50:08.849+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:50:08.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.068 seconds
[2024-05-18T11:50:39.885+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:50:39.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:50:39.921+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:50:39.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:50:40.039+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:50:40.007+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:50:40.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:50:40.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.341 seconds
[2024-05-18T11:51:10.546+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:51:10.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:51:10.572+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:51:10.571+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:51:10.940+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:51:10.857+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:51:10.983+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:51:11.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.729 seconds
[2024-05-18T11:51:42.050+0000] {processor.py:161} INFO - Started process (PID=398) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:51:42.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:51:42.059+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:51:42.057+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:51:42.154+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:51:42.129+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:51:42.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:51:42.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.232 seconds
[2024-05-18T11:52:12.809+0000] {processor.py:161} INFO - Started process (PID=405) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:52:12.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:52:12.824+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:52:12.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:52:12.924+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:52:12.896+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:52:12.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:52:13.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.270 seconds
[2024-05-18T11:52:43.311+0000] {processor.py:161} INFO - Started process (PID=413) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:52:43.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:52:43.340+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:52:43.339+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:52:43.491+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:52:43.450+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:52:43.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:52:43.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.343 seconds
[2024-05-18T11:53:14.724+0000] {processor.py:161} INFO - Started process (PID=421) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:53:14.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:53:14.804+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:53:14.802+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:53:15.152+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:53:15.070+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:53:15.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:53:15.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 1.079 seconds
[2024-05-18T11:53:46.646+0000] {processor.py:161} INFO - Started process (PID=428) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:53:46.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:53:46.689+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:53:46.686+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:53:46.866+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:53:46.825+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:53:46.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:53:47.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.443 seconds
[2024-05-18T11:54:17.636+0000] {processor.py:161} INFO - Started process (PID=435) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:54:17.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:54:17.641+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:54:17.640+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:54:17.663+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:54:17.657+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:54:17.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:54:17.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.062 seconds
[2024-05-18T11:54:48.130+0000] {processor.py:161} INFO - Started process (PID=442) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:54:48.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:54:48.135+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:54:48.134+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:54:48.159+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:54:48.152+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:54:48.162+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:54:48.186+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.064 seconds
[2024-05-18T11:55:18.609+0000] {processor.py:161} INFO - Started process (PID=449) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:55:18.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:55:18.613+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:55:18.613+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:55:18.638+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:55:18.630+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:55:18.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:55:18.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.067 seconds
[2024-05-18T11:55:48.881+0000] {processor.py:161} INFO - Started process (PID=456) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:55:48.882+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:55:48.884+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:55:48.883+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:55:48.902+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:55:48.897+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:55:48.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:55:48.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-18T11:56:19.044+0000] {processor.py:161} INFO - Started process (PID=464) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:56:19.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:56:19.047+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:56:19.046+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:56:19.066+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:56:19.061+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:56:19.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:56:19.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-18T11:56:49.226+0000] {processor.py:161} INFO - Started process (PID=471) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:56:49.227+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:56:49.229+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:56:49.228+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:56:49.251+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:56:49.245+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:56:49.253+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:56:49.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-05-18T11:57:19.419+0000] {processor.py:161} INFO - Started process (PID=478) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:57:19.420+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:57:19.422+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:57:19.421+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:57:19.439+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:57:19.434+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:57:19.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:57:19.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.044 seconds
[2024-05-18T11:57:49.589+0000] {processor.py:161} INFO - Started process (PID=485) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:57:49.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:57:49.592+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:57:49.591+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:57:49.610+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:57:49.605+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:57:49.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:57:49.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-18T11:58:19.859+0000] {processor.py:161} INFO - Started process (PID=492) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:58:19.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:58:19.861+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:58:19.861+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:58:19.878+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:58:19.874+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:58:19.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:58:19.895+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-18T11:58:50.090+0000] {processor.py:161} INFO - Started process (PID=499) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:58:50.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:58:50.094+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:58:50.094+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:58:50.115+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:58:50.110+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:58:50.117+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:58:50.138+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.058 seconds
[2024-05-18T11:59:20.267+0000] {processor.py:161} INFO - Started process (PID=506) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:59:20.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:59:20.270+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:59:20.269+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:59:20.288+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:59:20.283+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:59:20.290+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:59:20.306+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-18T11:59:50.465+0000] {processor.py:161} INFO - Started process (PID=513) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T11:59:50.466+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T11:59:50.468+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:59:50.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T11:59:50.486+0000] {logging_mixin.py:188} INFO - [2024-05-18T11:59:50.481+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T11:59:50.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T11:59:50.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-18T12:00:20.689+0000] {processor.py:161} INFO - Started process (PID=520) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:00:20.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:00:20.693+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:00:20.692+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:00:20.765+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:00:20.745+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:00:20.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:00:20.829+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.155 seconds
[2024-05-18T12:00:51.009+0000] {processor.py:161} INFO - Started process (PID=527) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:00:51.010+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:00:51.012+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:00:51.012+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:00:51.028+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:00:51.024+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:00:51.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:00:51.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-18T12:01:21.182+0000] {processor.py:161} INFO - Started process (PID=534) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:01:21.183+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:01:21.184+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:01:21.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:01:21.203+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:01:21.198+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:01:21.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:01:21.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-18T12:01:51.346+0000] {processor.py:161} INFO - Started process (PID=541) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:01:51.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:01:51.349+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:01:51.349+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:01:51.366+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:01:51.362+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:01:51.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:01:51.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-18T12:02:21.492+0000] {processor.py:161} INFO - Started process (PID=548) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:02:21.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:02:21.495+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:02:21.495+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:02:21.512+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:02:21.508+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:02:21.514+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:02:21.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.046 seconds
[2024-05-18T12:02:51.705+0000] {processor.py:161} INFO - Started process (PID=555) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:02:51.706+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:02:51.708+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:02:51.708+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:02:51.727+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:02:51.723+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:02:51.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:02:51.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.049 seconds
[2024-05-18T12:03:21.857+0000] {processor.py:161} INFO - Started process (PID=562) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:03:21.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:03:21.861+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:03:21.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:03:21.879+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:03:21.875+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:03:21.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:03:21.895+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-18T12:03:52.064+0000] {processor.py:161} INFO - Started process (PID=569) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:03:52.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:03:52.071+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:03:52.071+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:03:52.089+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:03:52.084+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:03:52.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:03:52.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.060 seconds
[2024-05-18T12:04:22.242+0000] {processor.py:161} INFO - Started process (PID=576) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:04:22.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:04:22.245+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:04:22.245+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:04:22.262+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:04:22.258+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:04:22.263+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:04:22.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-18T12:04:52.439+0000] {processor.py:161} INFO - Started process (PID=583) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:04:52.440+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:04:52.442+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:04:52.442+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:04:52.460+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:04:52.455+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:04:52.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:04:52.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-18T12:05:22.600+0000] {processor.py:161} INFO - Started process (PID=590) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:05:22.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:05:22.604+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:05:22.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:05:22.622+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:05:22.617+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:05:22.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:05:22.641+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-18T12:05:52.778+0000] {processor.py:161} INFO - Started process (PID=597) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:05:52.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:05:52.781+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:05:52.780+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:05:52.799+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:05:52.794+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:05:52.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:05:52.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-18T12:06:22.938+0000] {processor.py:161} INFO - Started process (PID=604) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:06:22.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:06:22.942+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:06:22.941+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:06:22.960+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:06:22.956+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:06:22.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:06:22.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.045 seconds
[2024-05-18T12:06:53.118+0000] {processor.py:161} INFO - Started process (PID=611) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:06:53.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:06:53.121+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:06:53.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:06:53.141+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:06:53.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:06:53.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:06:53.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-18T12:07:23.277+0000] {processor.py:161} INFO - Started process (PID=618) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:07:23.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:07:23.279+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:07:23.279+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:07:23.298+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:07:23.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:07:23.300+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:07:23.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-18T12:07:53.505+0000] {processor.py:161} INFO - Started process (PID=625) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:07:53.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:07:53.508+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:07:53.508+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:07:53.526+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:07:53.521+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:07:53.528+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:07:53.552+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.052 seconds
[2024-05-18T12:08:23.663+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:08:23.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:08:23.666+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:08:23.666+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:08:23.683+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:08:23.679+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:08:23.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:08:23.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-18T12:08:53.846+0000] {processor.py:161} INFO - Started process (PID=639) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:08:53.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:08:53.849+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:08:53.848+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:08:53.865+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:08:53.861+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:08:53.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:08:53.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.041 seconds
[2024-05-18T12:09:24.006+0000] {processor.py:161} INFO - Started process (PID=646) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:09:24.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:09:24.009+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:09:24.008+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:09:24.027+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:09:24.022+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:09:24.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:09:24.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.043 seconds
[2024-05-18T12:09:54.235+0000] {processor.py:161} INFO - Started process (PID=653) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:09:54.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:09:54.238+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:09:54.238+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:09:54.256+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:09:54.251+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:09:54.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:09:54.272+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.042 seconds
[2024-05-18T12:10:24.400+0000] {processor.py:161} INFO - Started process (PID=660) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:10:24.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:10:24.403+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:10:24.402+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:10:24.422+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:10:24.416+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:10:24.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:10:24.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.048 seconds
[2024-05-18T12:10:54.595+0000] {processor.py:161} INFO - Started process (PID=667) to work on /opt/airflow/dags/test_dag.py
[2024-05-18T12:10:54.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/test_dag.py for tasks to queue
[2024-05-18T12:10:54.597+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:10:54.597+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/test_dag.py
[2024-05-18T12:10:54.614+0000] {logging_mixin.py:188} INFO - [2024-05-18T12:10:54.610+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/test_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/test_dag.py", line 8, in <module>
    from crawl import get_price,urls
  File "/opt/airflow/dags/crawl.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-05-18T12:10:54.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/test_dag.py
[2024-05-18T12:10:54.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/test_dag.py took 0.050 seconds
