[2024-06-07T06:36:56.085+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-07T06:36:56.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.task3 scheduled__2024-05-30T16:53:00+00:00 [queued]>
[2024-06-07T06:36:56.130+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.task3 scheduled__2024-05-30T16:53:00+00:00 [queued]>
[2024-06-07T06:36:56.134+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-07T06:36:56.158+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): task3> on 2024-05-30 16:53:00+00:00
[2024-06-07T06:36:56.171+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'task3', 'scheduled__2024-05-30T16:53:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmpmv8q229b']
[2024-06-07T06:36:56.176+0000] {standard_task_runner.py:91} INFO - Job 155: Subtask task3
[2024-06-07T06:36:56.171+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-07T06:36:56.180+0000] {standard_task_runner.py:63} INFO - Started process 111 to run task
[2024-06-07T06:36:56.265+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.task3 scheduled__2024-05-30T16:53:00+00:00 [running]> on host c0a906348550
[2024-06-07T06:36:56.450+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='task3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T16:53:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T16:53:00+00:00'
[2024-06-07T06:36:56.454+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-07T06:36:56.480+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-07T06:36:56.481+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_dag.py", line 19, in print_crawl
    prices[currency] = get_price(link, currency)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_price() takes 1 positional argument but 2 were given
[2024-06-07T06:36:56.517+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=my_dag, task_id=task3, run_id=scheduled__2024-05-30T16:53:00+00:00, execution_date=20240530T165300, start_date=20240607T063656, end_date=20240607T063656
[2024-06-07T06:36:56.555+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 155 for task task3 (get_price() takes 1 positional argument but 2 were given; 111)
[2024-06-07T06:36:56.571+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-07T06:36:56.606+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-07T06:36:56.610+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
